# Generated by Django 5.2.13 on 2026-05-01 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_notes_alter_lead_assigned_to_alter_lead_email_and_more'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
