# Generated by Django 5.2.13 on 2026-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_notes_quotation_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='gst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_rate',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
