# Generated by Django 5.2.11 on 2026-05-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_camp_package_camp'),
        ('quotations', '0003_quotation_gst_amount_quotation_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='hotels.camp'),
        ),
    ]
