# Generated by Django 5.2.13 on 2026-05-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('trek_package', 'Trek Package'), ('equipment', 'Equipment'), ('meal_plan', 'Meal Plan'), ('transport', 'Transport'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50)),
                ('stock', models.IntegerField(default=0, help_text='Units in stock. 0 = out of stock.')),
                ('discount_pct', models.FloatField(default=0, help_text='Discount percentage (0–100).')),
                ('is_active', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='treks.camp')),
            ],
        ),
    ]
