# Generated by Django 5.2.13 on 2026-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('service', 'Service'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_pct',
            field=models.FloatField(default=0, help_text='Discount percentage (0–100).'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Units in stock. 0 = out of stock.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
