# Generated by Django 5.2.11 on 2026-05-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_camp_package_camp'),
        ('products', '0002_product_category_product_discount_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='hotels.camp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('trek_package', 'Trek Package'), ('equipment', 'Equipment'), ('meal_plan', 'Meal Plan'), ('transport', 'Transport'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
