# Generated by Django 5.2.11 on 2026-05-21 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('gst_rate', models.FloatField(default=18)),
                ('gst_amount', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
            ],
        ),
    ]
