# Generated by Django 5.2.13 on 2026-05-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_rate',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
