# Generated by Django 5.2.11 on 2026-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales'), ('camp_leader', 'Camp Leader'), ('trekker', 'Trekker')], default='sales', max_length=20),
        ),
    ]
