# Generated by Django 5.2.11 on 2026-05-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_camp_package_camp'),
        ('leads', '0004_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hotels.camp'),
        ),
    ]
