# Generated by Django 5.2.11 on 2026-05-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('standard', 'Standard Group'), ('private', 'Private Expedition'), ('luxury', 'Luxury Camp'), ('student', 'Student/Youth Special')], default='standard', max_length=30)),
                ('price_per_person', models.FloatField()),
                ('max_trekkers', models.IntegerField(default=15)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_per_person'],
            },
        ),
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('region', models.CharField(db_index=True, help_text='e.g. Uttarakhand, Ladakh, Himachal', max_length=100)),
                ('base_camp', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('expert', 'Expert / Technical')], default='moderate', max_length=20)),
                ('duration_days', models.IntegerField(default=5)),
                ('max_altitude', models.IntegerField(default=3000, help_text='Altitude in meters')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='Inclusions: ["Guide","Equipment","Meals"]')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of adventure image URLs')),
                ('price_min', models.FloatField(default=0, help_text='Starting price per person')),
                ('price_max', models.FloatField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-avg_rating'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=12, unique=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('check_in', models.DateField(verbose_name='Start Date')),
                ('check_out', models.DateField(verbose_name='End Date')),
                ('trekkers_count', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('on_trek', 'On Trek'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, default='', help_text='Medical issues, dietary needs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='leads.lead')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.package')),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.trek')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('travel_type', models.CharField(blank=True, default='solo', help_text='solo, group, family, couple', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.booking')),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.trek')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.trek'),
        ),
    ]
