# Generated by Django 5.2.11 on 2026-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='route_plan',
            field=models.JSONField(blank=True, default=list, help_text='Detailed itinerary: [{"day": 1, "title": "...", "desc": "..."}]'),
        ),
    ]
