# Generated by Django 5.2.11 on 2026-05-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_trek_route_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('experience_years', models.IntegerField(default=5)),
                ('rating', models.FloatField(default=4.8)),
                ('specialty', models.CharField(blank=True, default='Elite Expeditions', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='hotels.camp'),
        ),
    ]
