# Generated by Django 5.2.11 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_camp_package_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='best_season',
            field=models.CharField(default='April - June', help_text='e.g. Sept - Nov', max_length=100),
        ),
        migrations.AddField(
            model_name='trek',
            name='weather_info',
            field=models.JSONField(blank=True, default=dict, help_text='Average weather: {"temp": "5°C", "condition": "Sunny", "humidity": "45%"}'),
        ),
    ]
