# Generated by Django 5.2.11 on 2026-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_trek_best_season_trek_weather_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='base_camp',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='route_plan',
            field=models.JSONField(blank=True, default=list, help_text='Package specific itinerary'),
        ),
    ]
